=== nharward/commons-j/src/test/resources/schema/rolodex.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://nerds.antelax.xmlns/rolodex" xmlns:tns="http://nerds.antelax.xmlns/rolodex" elementFormDefault="qualified">
    <complexType name="person-type">
        <sequence>
            <element name="last-name" type="string" maxOccurs="1" minOccurs="1" />
            <element name="first-name" type="string" maxOccurs="1" minOccurs="0" />
            <element name="address" type="tns:address-type" maxOccurs="unbounded" minOccurs="0"></element>
        </sequence>
    </complexType>
    <complexType name="address-type">
        <sequence>
            <element name="line" type="string" maxOccurs="unbounded" minOccurs="0" />
            <element name="city" type="string" maxOccurs="1" minOccurs="0" />
            <element name="state" type="string" maxOccurs="1" minOccurs="0" />
            <element name="zipcode" type="positiveInteger" maxOccurs="1" minOccurs="0" />
        </sequence>
        <attribute name="type" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="home" />
                    <enumeration value="business" />
                    <enumeration value="mailing" />
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="contact-list">
        <choice>
            <element name="person" type="tns:person-type" maxOccurs="unbounded" minOccurs="0"></element>
        </choice>
    </complexType>
    <element name="contacts" type="tns:contact-list"></element>
</schema>

=== nharward/commons-j/src/test/resources/rolodex.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
// Copyright 2013 Nathaniel Harward
//
// This file is part of commons-j.
//
// commons-j is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// commons-j is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with commons-j. If not, see <http://www.gnu.org/licenses/>.
-->
<r:contacts xmlns:r="http://nerds.antelax.xmlns/rolodex" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nerds.antelax.xmlns/rolodex ../schema/rolodex.xsd ">
    <!--  This is a comment about all contacts -->
    <r:person>
        <!--  This is a comment about John Doe -->
        <r:last-name>Doe</r:last-name>
        <r:first-name>John</r:first-name>
        <r:address type="home">
            <r:line>12345 Main St.</r:line>
            <r:city>Nowhere</r:city>
            <r:state>Nohow</r:state>
            <r:zipcode>12345</r:zipcode>
        </r:address>
        <r:address type="business">
            <r:line>54321 Main St.</r:line>
            <r:city>Nowhere</r:city>
            <r:state>Nohow</r:state>
            <r:zipcode>12345</r:zipcode>
        </r:address>
    </r:person>
    <r:person>
        <!--  This is a comment about Jane Doe -->
        <r:last-name>Doe</r:last-name>
        <r:first-name>Jane</r:first-name>
        <r:address type="home">
            <r:line>12345 Main St.</r:line>
            <r:city>Nowhere</r:city>
            <r:state>Nohow</r:state>
            <r:zipcode>12345</r:zipcode>
        </r:address>
        <r:address type="business">
            <r:line>1234 Nowhere Street</r:line>
            <r:city>Some City</r:city>
            <r:state>Some State</r:state>
            <r:zipcode>12345</r:zipcode>
        </r:address>
    </r:person>
</r:contacts>
